export type ReferenceType="technique"|"color"|"shape"|"style"|"makeup"|"pmu"|"hairstyle"|"other";
export type PilotReference={id:string;serviceId:string;type:ReferenceType;nameFa:string;nameEn:string;technicalDefinition:string;visualRules:string[];generationRules:string[];negativeConstraints:string[];active:boolean;images:{id:string;url:string;isPrimary:boolean;sortOrder:number}[]};
const ref=(id:string,serviceId:string,type:ReferenceType,nameFa:string,nameEn:string,technicalDefinition:string,visualRules:string[],negativeConstraints:string[],generationRules:string[]=[]):PilotReference=>({id,serviceId,type,nameFa,nameEn,technicalDefinition,visualRules,generationRules,negativeConstraints,active:true,images:[]});
export const pilotReferences:PilotReference[]=[
 ref("balayage","hair-color","technique","بالیاژ","Balayage","Balayage is a gradual lightening technique in which the root generally remains darker and more natural, with increasing brightness from the mid-lengths toward the ends.",["soft gradual transition","no hard horizontal boundary","darker / natural root","brighter mid-lengths and ends","natural irregular highlighted distribution","no traditional stripe-like highlighting"],["no hard highlight stripes","no full-root bleaching unless separately selected","do not change face identity","do not change haircut unless haircut is separately selected"],["Controls technique only; take color tone from a separate color reference."]),
 ref("spiky-lashes","lashes","style","مژه اسپایکی","Spiky Lashes","A lash-extension style with clearly separated narrow spikes created by intentionally longer lash sections among shorter lashes.",["visible individual spikes","alternating shorter lashes and longer spikes","separated / textured appearance","adjustable intensity based on user preference"],["do not turn into uniform Volume lashes","do not change eye shape","do not change iris color","do not alter brows","change eyelashes only"]),
 ref("graduated-bob","haircut","style","باب گرَجوشن","Graduated Bob","Structured bob haircut with shorter hair in the back and gradually increasing length toward the front.",["shorter rear section","gradually longer front","layered graduation in the back","visible volume around the occipital area","can range from soft to more angular"],["do not change hair color","preserve face identity","only modify hair length / haircut structure"]),
 ref("light-makeup","makeup","makeup","میکاپ لایت","Light Makeup","Light and natural makeup focused on improving freshness and balance without a heavy or artificial appearance.",["lightweight natural base","concealer only where needed","subtle blush","natural brows","light mascara","subtle eyeliner","neutral / light eyeshadow","natural lipstick or tint","preserve realistic skin texture"],["no heavy contour","no full glam","no plastic skin","no facial identity change"]),
 ref("microblading","brows","pmu","بلید ابرو","Microblading","Semi-permanent eyebrow styling using very thin hair-like strokes to visually simulate natural eyebrow hairs.",["fine hair strokes","natural direction","fill sparse areas","respect existing eyebrow structure","design must fit the person's face"],["no block eyebrow","no solid tattoo-like fill","do not radically alter face structure"]),
 ref("lip-shading","lip","pmu","شیدینگ لب","Lip Shading","Semi-permanent lip color treatment designed to create gradual, even, soft and natural-looking lip color.",["soft tonal transition","even but natural color","retain lip texture","fresh appearance"],["do not change lip volume","do not reshape lips","no harsh lipstick border","no artificial overlining"]),
 ref("almond-nails","nails","shape","ناخن بادامی","Almond Nails","Nail shape with gradually tapered sides and a narrow but softly rounded tip resembling an almond.",["tapered sides","narrow tip","rounded / soft tip","usually medium-to-long appearance","visually elongates fingers"],["do not turn into Stiletto","no needle-sharp point","preserve fingers","preserve hand anatomy","preserve skin"],["Controls shape only."]),
 ref("half-up","updo","hairstyle","شینیون موی باز","Open / Half-up Hairstyle","A hairstyle in which a substantial part of the hair remains open while another part is styled through twisting, braiding, gathering or shaping.",["significant amount of hair stays down/open","upper or side sections may be styled","soft / romantic / formal appearance"],["do not convert to fully closed updo","preserve hair color unless separately changed","preserve identity"]),
 ref("icy-hair","hair-color","color","رنگ موی یخی","Icy Hair Color","Very cool and light blonde/silver hair-color family with white, silver or cool-gray undertones.",["very cool tonality","pale icy brightness","silver / white / cool-gray undertone","preserve realistic texture and highlights"],["no yellow warmth","no golden warmth","no honey","no orange","no flat pure white","do not change haircut"],["Controls color only."]),
 ref("red-nails","nails","color","خانواده قرمز ناخن","Red Nail Color Family","A nail-color family covering a controlled range from lighter coral/red shades through true red, raspberry, brick, burgundy, maroon and deep red.",["preserve selected shade identity","maintain realistic polish reflections","color should match selected swatch/reference closely"],["do not modify nail shape","do not modify finger anatomy","lighting must not materially change the selected red tone"],["Controls color only."])
];
