import Link from "next/link";
import { BookImage, Brush, ExternalLink, Images, Settings, Sparkles, Upload, Video } from "lucide-react";
import { Brand } from "@/components/Brand";
import { services } from "@/lib/catalog";
import { demoTenant } from "@/lib/tenant";
import "./admin.css";
const sections=[{title:"برند و مشاور",en:"Brand & Consultant",icon:Brush,copy:"نام، آواتار، لوگو، رنگ‌ها و راه‌های ارتباطی"},{title:"کتابخانه مرجع",en:"Reference Library",icon:BookImage,copy:"تصاویر مرجع، مرجع اصلی، قوانین و Prompt"},{title:"امضای مروا",en:"Portfolio",icon:Images,copy:"کارهای واقعی سالن؛ مستقل از شبیه‌سازی"},{title:"تنظیمات تولید",en:"Generation Settings",icon:Sparkles,copy:"سهمیه رایگان و وضعیت سرویس Mock"},{title:"مدیریت خدمات",en:"Service Management",icon:Settings,copy:"دسته‌ها، گزینه‌های دو زبانه و ترتیب نمایش"}];
export default function Admin(){return <main className="admin"><aside><Brand admin/><nav>{sections.map(({title,icon:Icon})=><a href={`#${title}`} key={title}><Icon/>{title}</a>)}</nav><Link href="/"><ExternalLink/> مشاهده آینه</Link></aside><div className="admin-content"><header><span>MIRROR CONTROL ROOM</span><h1>مدیریت تجربه آینه مروا</h1><p>تمام داده‌ها برای tenant دمو نمایش داده می‌شن و اتصال Supabase بعداً جایگزین fallback محلی می‌شه.</p></header><section className="admin-stats"><article><b>{services.length}</b><span>لاین فعال</span></article><article><b>{services.reduce((n,s)=>n+s.decisions.flatMap(d=>d.groups.flatMap(g=>g.options)).length,0)}</b><span>گزینه دو زبانه</span></article><article><b>۱ + ۲</b><span>سهمیه رایگان</span></article></section>{sections.map(({title,en,icon:Icon,copy},i)=><section className="admin-panel" id={title} key={title}><div className="panel-title"><span><Icon/></span><div><h2>{title}</h2><small>{en}</small><p>{copy}</p></div><button>ویرایش</button></div>{i===0&&<div className="settings-grid"><Field label="نام مشاور" value={demoTenant.consultant.name}/><Field label="English name" value={demoTenant.consultant.englishName}/><Field label="نام سالن" value={demoTenant.salonName}/><Field label="ویدئوی خوش‌آمد" value={demoTenant.consultant.videoUrl}/><Field label="پوستر" value={demoTenant.consultant.posterUrl||""}/><button className="upload"><Video/><span>جایگزینی ویدئو<small>MP4 · از تنظیمات tenant</small></span><Upload/></button></div>}{i===1&&<div className="admin-list">{services.slice(0,4).map(s=><div key={s.id}><b>{s.nameFa}<small>{s.nameEn}</small></b><span>{s.decisions.flatMap(d=>d.groups.flatMap(g=>g.options)).length} مرجع آماده</span><button>مدیریت</button></div>)}</div>}{i===2&&<div className="empty-admin"><Images/><span>تصاویر پورتفولیو را بارگذاری، دسته‌بندی و مرتب کن.</span><button>بارگذاری عکس</button></div>}{i===3&&<div className="settings-grid"><Field label="قبل از لید" value={String(demoTenant.limits.anonymous)}/><Field label="بعد از لید" value={String(demoTenant.limits.extraAfterLead)}/><Field label="حداکثر" value={String(demoTenant.limits.maximum)}/><Field label="Provider" value="Mock · فعال"/></div>}{i===4&&<div className="admin-list">{services.map(s=><div key={s.id}><b>{s.nameFa}<small>{s.nameEn}</small></b><span>{s.enabled?"فعال":"غیرفعال"}</span><button>ویرایش</button></div>)}</div>}</section>)}</div></main>}
function Field({label,value}:{label:string;value:string}){return <label>{label}<input defaultValue={value}/></label>}
