import Link from "next/link";
import { ArrowLeft, BarChart3, Brush, ChevronLeft, Eye, Image, MessageCircle, Settings, Sparkles, Upload } from "lucide-react";
import { Brand } from "@/components/Brand";
import { demoTenant } from "@/lib/tenant";
import { services } from "@/lib/catalog";
import "./admin.css";

const stats=[{label:"بازدیدها",value:"۲,۴۸۰",delta:"۱۲٪",icon:Eye},{label:"شروع تجربه",value:"۱,۶۲۰",delta:"۸٪",icon:Sparkles},{label:"شبیه‌سازی",value:"۸۴۳",delta:"۱۷٪",icon:Image},{label:"درخواست مشاوره",value:"۱۲۶",delta:"۹٪",icon:MessageCircle}];
export default function Admin(){return <main className="dashboard"><aside><Brand admin/><nav><a className="active"><BarChart3/>نمای کلی</a><a><Sparkles/>لاین‌ها و گزینه‌ها</a><a><MessageCircle/>درخواست‌های مشاوره</a><a><Brush/>برند و مشاور</a><a><Settings/>تنظیمات</a></nav><Link href="/" className="back-app">مشاهده اپ <ArrowLeft/></Link></aside><div className="admin-main"><header><div><span>دوشنبه، ۱۶ شهریور</span><h1>سلام، روزت بخیر 👋</h1></div><button>خروجی گزارش</button></header><section className="stats">{stats.map(({label,value,delta,icon:Icon})=><article key={label}><div><span>{label}</span><Icon/></div><b>{value}</b><small><i>↑ {delta}</i> نسبت به ماه قبل</small></article>)}</section><section className="admin-grid"><article className="chart-card"><div className="card-head"><div><b>عملکرد تجربه</b><span>۳۰ روز گذشته</span></div><select><option>این ماه</option></select></div><div className="chart"><div className="bars">{[40,58,45,76,64,82,73,92,68,87,71,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="axis"><span>۱ شهریور</span><span>۱۵ شهریور</span><span>۳۰ شهریور</span></div></div></article><article className="conversion"><span>نرخ تبدیل</span><div className="donut"><b>۷.۸٪</b><small>از بازدید به لید</small></div><p><i/>۱۲۶ درخواست از ۱,۶۲۰ شروع</p></article></section><section className="admin-grid lower"><article><div className="card-head"><div><b>محبوب‌ترین لاین‌ها</b><span>براساس انتخاب کاربران</span></div><button>مدیریت لاین‌ها <ChevronLeft/></button></div><div className="service-rows">{services.slice(0,4).map((s,i)=><div key={s.id}><span>۰{i+1}</span><b>{s.title}</b><div><i style={{width:`${90-i*17}%`}}/></div><em>{["۳۸٪","۲۴٪","۱۸٪","۱۲٪"][i]}</em></div>)}</div></article><article className="quick"><b>شخصی‌سازی سریع</b><button><span className="consultant-mini">{demoTenant.consultant.initials}</span><div><b>{demoTenant.consultant.name}</b><small>مشاور فعال</small></div><ChevronLeft/></button><button><i className="palette"/><div><b>تم گرم کرم</b><small>رنگ‌بندی فعال</small></div><ChevronLeft/></button><button><Upload/><div><b>ویدئوی خوش‌آمد</b><small>جای‌نگهدار فعال</small></div><ChevronLeft/></button></article></section><section className="settings-card"><div><b>محدودیت شبیه‌سازی رایگان</b><span>تعداد نتایج قابل ساخت برای کاربر ناشناس و کاربر دارای اطلاعات تماس</span></div><label>بدون اطلاعات <input defaultValue={demoTenant.limits.anonymous}/></label><label>بعد از ثبت تماس <input defaultValue={demoTenant.limits.withContact}/></label><button>ذخیره تغییرات</button></section></div></main>}
