"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Camera, Check, ChevronLeft, Eye, Flower2, Gift, Hand, Heart, Image as ImageIcon, Images, ScanFace, Scissors, Sparkles, Upload, Volume2, VolumeX, WandSparkles } from "lucide-react";
import { Brand } from "@/components/Brand";
import { MirrorButton, MirrorCard, MirrorFrame, MirrorGlow, MirrorIcon, MirrorModal, MirrorProgress, MirrorTile } from "@/components/mirror/MirrorUI";
import { getOption, services } from "@/lib/catalog";
import { demoTenant } from "@/lib/tenant";
import { ImageAsset, PhotoType, RecommendationMode } from "@/lib/types";
import { favoriteBeautySimulation, generateBeautySimulation, SimulationResult } from "@/lib/simulation/service";
import { getPublicPortfolio, PublicPortfolioItem } from "@/lib/portfolio/public";
import { createPublicLead, PublicLeadInput } from "@/lib/leads/public";
import { IRANIAN_MOBILE_ERROR, isValidIranianMobile, normalizeIranianMobile } from "@/lib/leads/mobile";
import { getEnabledPublicServices } from "@/lib/services/public";
import type { Service } from "@/lib/types";

type Step="welcome"|"main"|"paths"|"recommend"|"services"|"requirement"|"detail"|"wizard"|"loading"|"result"|"portfolio"|"offers";
type Journey="recommend"|"self";
const icons={sparkles:Sparkles,scissors:Scissors,"scan-face":ScanFace,eye:Eye,flower:Flower2,hand:Hand,heart:Heart,wand:WandSparkles};
const recs:{id:RecommendationMode;nameFa:string;nameEn:string;copy:string}[]=[{id:"natural",nameFa:"طبیعی",nameEn:"Natural",copy:"تغییری ظریف، هماهنگ و کم‌ریسک"},{id:"medium",nameFa:"متوسط",nameEn:"Medium",copy:"تغییری مشخص و متعادل که همچنان کاملاً شبیه توست"},{id:"bold",nameFa:"جسورانه",nameEn:"Bold",copy:"تغییری چشمگیر، اما همچنان هماهنگ با تو"}];
export default function Home(){
 const [step,setStep]=useState<Step>("welcome"),[history,setHistory]=useState<Step[]>([]),[journey,setJourney]=useState<Journey>(),[videoDone,setVideoDone]=useState(false),[muted,setMuted]=useState(true),[videoError,setVideoError]=useState(false),[primaryImages,setPrimaryImages]=useState<Partial<Record<"face"|"hand",ImageAsset>>>({}),[detailImages,setDetailImages]=useState<ImageAsset[]>([]),[consent,setConsent]=useState(false),[serviceId,setServiceId]=useState(""),[decision,setDecision]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[mode,setMode]=useState<RecommendationMode>(),[leadOpen,setLeadOpen]=useState(false),[leadDone,setLeadDone]=useState(false),[slider,setSlider]=useState(50),[generationCount,setGenerationCount]=useState(0),[currentGeneration,setCurrentGeneration]=useState<SimulationResult>(),[generationError,setGenerationError]=useState(""),[favoriteState,setFavoriteState]=useState<"idle"|"saving"|"liked"|"error">("idle"),[availableServices,setAvailableServices]=useState<Service[]|null>(null),[availabilityFailed,setAvailabilityFailed]=useState(false); const galleryRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),generationPending=useRef(false); const inputRole=useRef<{type:PhotoType;source:"camera"|"gallery"}>({type:"face",source:"gallery"});
 const service=services.find(s=>s.id===serviceId),current=service?.decisions[decision],requirement=journey==="recommend"?services.find(s=>s.photoRequirements.primaryType==="face")?.photoRequirements:service?.photoRequirements,detailType=journey==="self"?requirement?.detailTypes[0]:undefined;
 const progress=useMemo(()=>({welcome:0,main:12,paths:25,recommend:38,services:38,requirement:72,detail:78,wizard:55,loading:90,result:100,portfolio:30,offers:30}[step]),[step]);
 const go=(s:Step)=>{window.history.pushState({marvaaStep:s},"");setHistory(h=>[...h,step]);setStep(s)},back=()=>{if(history.length)window.history.back();else setStep("welcome")};
 const openFile=(type:PhotoType,source:"camera"|"gallery")=>{inputRole.current={type,source};(source==="camera"?cameraRef:galleryRef).current?.click()};
 const file=(f?:File)=>{if(!f)return;const {type,source}=inputRole.current,reader=new FileReader();reader.onload=()=>{const asset:ImageAsset={id:`${type}-${Date.now()}`,type,dataUrl:String(reader.result),source,role:type==="face"||type==="hand"?"primary":"detail"};if(asset.role==="primary")setPrimaryImages(x=>({...x,[type]:asset}));else setDetailImages(x=>[...x.filter(i=>i.type!==type),asset]);if(step==="requirement"){if(journey==="recommend")createWithPrimary(asset,{},mode);else if(detailType)go("detail");else createWithPrimary(asset,answers)}else if(step==="detail")create(answers)};reader.readAsDataURL(f)};
 const chooseService=(id:string)=>{setServiceId(id);setDecision(0);setAnswers({});go("wizard")};
 const selectOption=(id:string)=>{if(!current)return;const next={...answers,[current.id]:id};setAnswers(next);if(service&&decision<service.decisions.length-1)setDecision(x=>x+1);else if(!primaryImages[service!.photoRequirements.primaryType])go("requirement");else if(service?.photoRequirements.optionalDetailImages)go("detail");else create(next)};
 const create=async(next=answers,nextMode=mode,providedPrimary?:ImageAsset)=>{if(generationPending.current)return;const primary=providedPrimary||(service?primaryImages[service.photoRequirements.primaryType]:primaryImages.face);if(!primary)return;generationPending.current=true;setGenerationError("");go("loading");try{const generated=await generateBeautySimulation({images:{primaryImage:primary,detailImages,referenceImages:[]},tenantId:demoTenant.id,serviceCategory:serviceId||"recommendation",selectedOptions:next,selectedReferences:Object.entries(next).map(([k,v])=>getOption(serviceId,k,v)?.referenceId).filter(Boolean) as string[],recommendationMode:nextMode,identityPreservationInstructions:service?.photoRequirements.identityPreservationRules});setCurrentGeneration(generated);setFavoriteState("idle");setGenerationCount(x=>x+1);setStep("result")}catch{setGenerationError("در اجرای تغییر مشکلی پیش آمد. لطفاً دوباره تلاش کنید.");setStep(nextMode?"recommend":"wizard")}finally{generationPending.current=false}};
 const createWithPrimary=async(primary:ImageAsset,next=answers,nextMode=mode)=>create(next,nextMode,primary);
 const favorite=async()=>{if(!currentGeneration||favoriteState==="saving"||favoriteState==="liked")return;setFavoriteState("saving");try{await favoriteBeautySimulation(demoTenant.id,currentGeneration.sessionId,currentGeneration.generationId);setFavoriteState("liked")}catch{setFavoriteState("error")}};
 const submitLead=async(contact:Omit<PublicLeadInput,"tenantId"|"serviceSlug"|"selectedOptions">)=>{await createPublicLead({...contact,tenantId:demoTenant.id,serviceSlug:serviceId||undefined,selectedOptions:answers});setLeadDone(true)};
 useEffect(()=>{Object.entries(demoTenant.theme).forEach(([k,v])=>document.documentElement.style.setProperty(`--${k}`,v))},[]);
 useEffect(()=>{const pop=()=>setHistory(h=>{const next=[...h];let previous=next.pop();while(previous==="loading")previous=next.pop();setStep(previous||"welcome");return next});window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[]);
 useEffect(()=>{if(step!=="services")return;let active=true;setAvailableServices(null);setAvailabilityFailed(false);getEnabledPublicServices(demoTenant.id).then(items=>{if(active)setAvailableServices(items)}).catch(()=>{if(active){setAvailableServices([]);setAvailabilityFailed(true)}});return()=>{active=false}},[step]);
 const inputs=<><input ref={cameraRef} hidden type="file" accept="image/*" capture="user" onChange={e=>file(e.target.files?.[0])}/><input ref={galleryRef} hidden type="file" accept="image/*" onChange={e=>file(e.target.files?.[0])}/></>;
 if(step==="welcome")return <main className="welcome"><MirrorGlow/><Brand/><section className={`welcome-scene ${videoDone?"revealed":"speaking"}`}><div className="assistant-presence"><video autoPlay muted={muted} playsInline preload="metadata" poster={demoTenant.consultant.posterUrl} src={demoTenant.consultant.videoUrl} onEnded={()=>setVideoDone(true)} onError={()=>{setVideoError(true);setVideoDone(true)}}/>{videoError&&<div className="video-fallback"><MirrorIcon/><span>MARVAA</span></div>}<div className="presence-vignette"/><div className="assistant-id"><b>MARVAA</b><small dir="ltr">Beauty AI Concierge</small></div><div className="video-actions"><button onClick={()=>setMuted(x=>!x)} aria-label={muted?"روشن کردن صدا":"بی‌صدا کردن"}>{muted?<VolumeX/>:<Volume2/>}</button><button onClick={()=>setVideoDone(true)}>رد کردن</button></div></div><div className="welcome-reveal"><div className="signature-mirror"><span>✦</span></div><p className="kicker">FUTURE MIRROR · آینه مروا</p><h1 className="text-hero">خودت، اما متفاوت ✦</h1><MirrorButton onClick={()=>go("main")}>بزن بریم</MirrorButton></div></section></main>;
 return <main className="app-shell"><MirrorGlow/><header className="flow-header"><button className="back" onClick={back}><ArrowRight/> برگشت</button><Brand/><button className="portfolio-link" onClick={()=>go("portfolio")}><Images/> امضای مروا</button></header><MirrorProgress value={progress}/><section className="stage">{inputs}
 {step==="main"&&<><Heading eyebrow="انتخاب تو" title="امروز دوست داری کدام مسیر را ببینی؟" text="آینه آینده، نمونه‌کارهای واقعی سالن و پیشنهادهای مروا همیشه از همین‌جا در دسترس‌اند."/><div className="main-choices"><MirrorTile nameFa="نسخه جدید خودم را ببینم" nameEn="See My New Version" icon={<Sparkles/>} onClick={()=>go("paths")}/><MirrorTile nameFa="نمونه‌کارهای سالن را ببینم" nameEn="View Salon Portfolio" icon={<Images/>} onClick={()=>go("portfolio")}/><MirrorTile nameFa="پیشنهادها و هدایا" nameEn="Offers & Rewards" icon={<Gift/>} onClick={()=>go("offers")}/></div></>}
 {step==="paths"&&<><Heading eyebrow="آینه باز شد" title="این بار، انتخاب با توئه." text="می‌خوای مروا برات بسازه یا خودت همه جزئیات رو انتخاب کنی؟"/><div className="major-paths"><MirrorTile nameFa="مروا برام بسازه" nameEn="Marvaa Creates My Style" icon={<Sparkles/>} onClick={()=>{setJourney("recommend");go("recommend")}}/><MirrorTile nameFa="خودم استایل می‌کنم" nameEn="I Style Myself" icon={<Hand/>} onClick={()=>{setJourney("self");go("services")}}/></div></>}
 {step==="recommend"&&<><Heading eyebrow="میزان تغییر" title="دوست داری تغییرت چقدر باشه؟" text="اول میزان تغییر رو انتخاب کن؛ بعد یک عکس واضح از چهره‌ت می‌گیریم."/>{generationError&&<div className="lead-error" role="alert">{generationError}</div>}<div className="recommend-states">{recs.map((r,i)=><button key={r.id} onClick={()=>{setMode(r.id);primaryImages.face?create({},r.id):go("requirement")}}><span>۰{i+1}</span><div><b>{r.nameFa}</b><small dir="ltr">{r.nameEn}</small><p>{r.copy}</p></div><i>✦</i></button>)}</div></>}
 {step==="services"&&<><Heading eyebrow="استایل خودت" title="از کجا شروع کنیم؟" text="هر سرویس عکس مناسب خودش رو می‌شناسه؛ هر بار فقط یک تصمیم."/>{availableServices===null?<MirrorCard><p>در حال دریافت خدمات…</p></MirrorCard>:availabilityFailed?<MirrorCard><p role="alert">در حال حاضر دریافت فهرست خدمات ممکن نیست. لطفاً کمی بعد دوباره تلاش کنید.</p></MirrorCard>:<div className="service-grid">{availableServices.map(s=>{const Icon=icons[s.icon as keyof typeof icons]||Sparkles;return <MirrorTile key={s.id} nameFa={s.nameFa} nameEn={s.nameEn} icon={<Icon/>} onClick={()=>chooseService(s.id)}/>})}</div>}</>}
 {step==="requirement"&&requirement&&<><Heading eyebrow={requirement.primaryType==="hand"?"عکس دست · Hand photo":"عکس چهره · Face photo"} title={requirement.primaryType==="hand"?"برای دیدن مدل ناخن روی دست خودت، یه عکس واضح از دستت لازم دارم.":"برای دیدن این تغییر روی خودت، یه عکس واضح از چهره‌ت لازم دارم."} text={requirement.primaryType==="face"&&["hair-color","haircut","updo"].includes(serviceId)?"موها هم تا جای ممکن کامل و واضح داخل کادر باشن.":"این تصویر، عکس اصلی نتیجه نهایی خواهد بود."}/><PhotoMirror type={requirement.primaryType} guidance={requirement.guidance.map(x=>x.nameFa)} camera={()=>openFile(requirement.primaryType,"camera")} gallery={()=>openFile(requirement.primaryType,"gallery")}/><Consent checked={consent} set={setConsent}/></>}
 {step==="detail"&&detailType&&<><Heading eyebrow="جزئیات اختیاری · Optional detail" title={detailCopy(detailType)} text="نتیجه نهایی همچنان بر پایه عکس کامل چهره‌ت ساخته می‌شه؛ این عکس فقط مرجع جزئیاته."/><PhotoMirror type={detailType} guidance={["نمای نزدیک و واضح","نور مناسب","بدون فیلتر"]} camera={()=>openFile(detailType,"camera")} gallery={()=>openFile(detailType,"gallery")} detail/><MirrorButton variant="ghost" onClick={()=>create(answers)}>رد کردن</MirrorButton></>}
 {step==="wizard"&&current&&<><Heading eyebrow={`${service?.nameFa} · ${decision+1} از ${service?.decisions.length}`} title={current.questionFa} text="کدومش بیشتر به چیزی که تو ذهنت هست نزدیکه؟"/>{generationError&&<div className="lead-error" role="alert">{generationError}</div>}<div className="option-groups">{current.groups.map(g=><section key={g.id}><h2>{g.nameFa}<small dir="ltr">{g.nameEn}</small></h2><div className="options">{g.options.filter(o=>o.active).map(x=><MirrorTile key={x.id} nameFa={x.nameFa} nameEn={x.nameEn} selected={answers[current.id]===x.id} onClick={()=>selectOption(x.id)}/>)}</div></section>)}</div></>}
 {step==="loading"&&<div className="mirror-loading" role="status" aria-live="polite"><div className="loading-mirror" aria-hidden="true"><div className="orbit orbit-gold"/><div className="orbit orbit-violet"/><div className="light-ribbon ribbon-one"/><div className="light-ribbon ribbon-two"/><i className="orbit-star star-one">✦</i><i className="orbit-star star-two">✦</i><i className="orbit-star star-three">✦</i><div className="gold-particles"><i/><i/><i/><i/><i/><i/><i/><i/></div><span className="center-star">✦</span></div><h1>در حال اجرای تغییرات...</h1><p>چند لحظه تا دیدن نسخه جدیدت</p><div className="loading-benefits"><span><i>✦</i>دقیق و طبیعی</span><span><i>✦</i>مثل خود تو</span></div></div>}
 {step==="result"&&<Result before={(service?primaryImages[service.photoRequirements.primaryType]:primaryImages.face)?.dataUrl||""} after={currentGeneration?.generatedImageUrl||""} slider={slider} setSlider={setSlider} generationCount={generationCount} leadDone={leadDone} another={()=>generationCount>=demoTenant.limits.anonymous&&!leadDone?setLeadOpen(true):go("paths")} lead={()=>setLeadOpen(true)} favorite={favorite} favoriteState={favoriteState}/> }
 {step==="portfolio"&&<Portfolio/>}{step==="offers"&&<Offers back={back}/>} {leadOpen&&<LeadModal done={leadDone} close={()=>setLeadOpen(false)} submit={submitLead}/>}</section><footer>{demoTenant.salonName} · تجربه‌ای امن، خصوصی و هوشمند</footer></main>
}
function detailCopy(t:PhotoType){return t==="brows-closeup"?"برای اینکه فرم و جزئیات ابرو دقیق‌تر دربیاد، یه عکس نزدیک از ابروهات هم بفرست.":t==="eyes-closeup"?"برای نتیجه دقیق‌تر، یه عکس نزدیک و واضح از چشم‌ها و مژه‌هات بفرست.":"برای جزئیات دقیق‌تر شیدینگ، می‌تونی یه عکس نزدیک از لب‌هات بفرستی."}
function PhotoMirror({type,guidance,camera,gallery,detail=false}:{type:PhotoType;guidance:string[];camera:()=>void;gallery:()=>void;detail?:boolean}){return <MirrorFrame className="capture"><MirrorIcon>{type==="hand"?<Hand/>:<ScanFace/>}</MirrorIcon><div className="tips">{guidance.map(x=><span key={x}>{x}</span>)}</div><MirrorButton onClick={camera}><Camera/> {detail?"گرفتن عکس نزدیک":type==="hand"?"همین الان عکس دست بگیر":"همین الان عکس بگیر"}</MirrorButton><MirrorButton variant="secondary" onClick={gallery}><Upload/> از گالری انتخاب کن</MirrorButton></MirrorFrame>}
function Consent({checked,set}:{checked:boolean;set:(x:boolean)=>void}){return <><label className="consent"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><span><b>اجازه ذخیره دائمی عکس</b><small>اختیاری — بدون این اجازه عکس فقط در همین تجربه استفاده می‌شه.</small></span></label><p className="privacy">عکس فقط برای ساخت شبیه‌سازی استفاده می‌شه و بدون اجازه تو برای هدف دیگه‌ای استفاده نمی‌شه.</p></>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="heading"><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Result({before,after,slider,setSlider,generationCount,leadDone,another,lead,favorite,favoriteState}:{before:string;after:string;slider:number;setSlider:(x:number)=>void;generationCount:number;leadDone:boolean;another:()=>void;lead:()=>void;favorite:()=>void;favoriteState:"idle"|"saving"|"liked"|"error"}){return <><Heading eyebrow="آینه آماده‌ست" title="این هنوز خودتی." text="خط روی تصویر رو بکش و قبل و بعد رو با هم ببین."/><MirrorFrame className="comparison"><img src={before} alt="من الان"/><div className="after" style={{clipPath:`inset(0 0 0 ${slider}%)`}}><img src={after} alt="نسخه جدید من"/></div><input aria-label="مقایسه قبل و بعد" type="range" min="0" max="100" value={slider} onChange={e=>setSlider(Number(e.target.value))}/><div className="divider" style={{left:`${slider}%`}}/><span className="before-label">من الان</span><span className="after-label">نسخه جدید من</span></MirrorFrame><div className="result-actions"><MirrorButton onClick={another}>یه نسخه دیگه ببینم</MirrorButton><MirrorButton variant="secondary" onClick={favorite} disabled={favoriteState==="saving"||favoriteState==="liked"}>{favoriteState==="saving"?"در حال ذخیره…":favoriteState==="liked"?"ذخیره شد ✓":"این استایل رو دوست دارم"}</MirrorButton>{favoriteState==="liked"&&<div className="favorite-feedback" role="status">این استایل به علاقه‌مندی‌های تو اضافه شد.</div>}{favoriteState==="error"&&<div className="lead-error" role="alert">ذخیره علاقه‌مندی انجام نشد. لطفاً دوباره تلاش کنید.</div>}<MirrorButton variant="ghost" onClick={lead}>مشاوره با مروا</MirrorButton></div><BeautyPassport/>{generationCount===1&&!leadDone&&<MirrorCard className="unlock"><b>دوست داری دو نسخه دیگه از خودت رو هم ببینی؟</b><p>راه ارتباطی‌ت رو بذار تا {demoTenant.limits.extraAfterLead} آینه دیگه باز بشه.</p><button onClick={lead}>باز کردن نسخه‌ها <ChevronLeft/></button></MirrorCard>}</>}
function BeautyPassport(){return <MirrorCard className="passport"><span>MARVAA BEAUTY ID</span><h2>پاسپورت زیبایی تو</h2><div><i>تناژ ترجیحی<small>در حال شناختن</small></i><i>شدت محبوب<small>متعادل</small></i><i>استایل‌های دوست‌داشتنی<small>۱ مورد</small></i></div></MirrorCard>}
function Portfolio(){const [cat,setCat]=useState("all"),[items,setItems]=useState<PublicPortfolioItem[]>([]);useEffect(()=>{getPublicPortfolio(demoTenant.id).then(setItems)},[]);const visible=cat==="all"?items:items.filter(x=>x.serviceId===cat);return <><Heading eyebrow="کارهای واقعی سالن" title="امضای مروا" text="این گالری از کتابخانه مرجع و شبیه‌سازی هوش مصنوعی کاملاً جداست."/><div className="portfolio-filters"><button className={cat==="all"?"active":""} onClick={()=>setCat("all")}><b>همه</b><small>All</small></button>{services.map(s=><button className={cat===s.id?"active":""} onClick={()=>setCat(s.id)} key={s.id}><b>{s.nameFa}</b><small dir="ltr">{s.nameEn}</small></button>)}</div><div className="portfolio-showcase">{visible.map(x=><MirrorFrame key={x.id}><img src={x.imageUrl} alt={x.titleFa}/><b>{x.titleFa}</b>{x.description&&<small>{x.description}</small>}</MirrorFrame>)}{visible.length===0&&<MirrorFrame><div className="portfolio-placeholder"><ImageIcon/><span>نمونه‌کاری برای نمایش نیست</span><small>محتوا از پنل مدیریت و بدون استقرار مجدد به‌روز می‌شود</small></div></MirrorFrame>}</div></>}
function Offers({back}:{back:()=>void}){return <><Heading eyebrow="پیشنهادها و هدایا" title="چیزهای دوست‌داشتنی در راه‌اند." text="به‌زودی پیشنهادهای واقعی و هدیه‌های سالن را همین‌جا می‌بینی."/><MirrorCard className="offers-empty"><MirrorIcon><Gift/></MirrorIcon><span>COMING SOON</span><h2>فعلاً پیشنهادی فعال نیست</h2><p>وقتی پیشنهاد تازه‌ای آماده شود، بدون نمایش تخفیف یا هدیه ساختگی در همین بخش قرار می‌گیرد.</p><MirrorButton variant="secondary" onClick={back}><ArrowRight/> بازگشت به انتخاب‌ها</MirrorButton></MirrorCard></>}
function LeadModal({close,submit,done}:{close:()=>void;submit:(contact:Omit<PublicLeadInput,"tenantId"|"serviceSlug"|"selectedOptions">)=>Promise<void>;done:boolean}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),name=String(form.get("name")||"").trim(),mobile=String(form.get("mobile")||"").trim();if(!name||!mobile){setError("لطفاً نام و شماره موبایل را وارد کنید.");return}if(!isValidIranianMobile(mobile)){setError(IRANIAN_MOBILE_ERROR);return}const normalizedMobile=normalizeIranianMobile(mobile);setSaving(true);setError("");try{await submit({name,mobile:normalizedMobile,whatsapp:String(form.get("whatsapp")||""),telegram:String(form.get("telegram")||"")})}catch{setError("ذخیره اطلاعات انجام نشد. لطفاً کمی بعد دوباره تلاش کنید.")}finally{setSaving(false)}}return <MirrorModal onClose={close}>{done?<div className="success"><MirrorIcon><Check/></MirrorIcon><h2>دو آینه دیگه برات باز شد</h2><p>حالا می‌تونی دو نسخه تازه هم ببینی.</p><MirrorButton onClick={close}>ادامه می‌دم</MirrorButton></div>:<form onSubmit={save}><span className="kicker">دو نسخه بیشتر</span><h2>چطور باهات در تماس باشیم؟</h2><p className="muted">اطلاعاتت فقط برای همین تجربه و پیگیری مشاوره استفاده می‌شه.</p><label>نام<input name="name" required placeholder="مثلاً سارا"/></label><label>شماره موبایل<input name="mobile" required inputMode="tel" placeholder="۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label><label>واتس‌اپ <small>اختیاری</small><input name="whatsapp" inputMode="tel"/></label><label>تلگرام <small>اختیاری</small><input name="telegram" dir="ltr"/></label>{error&&<div className="lead-error" role="alert">{error}</div>}<MirrorButton type="submit" disabled={saving}>{saving?"در حال ذخیره…":"باز کردن دو نسخه"}</MirrorButton></form>}</MirrorModal>}
