"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronLeft, Eye, Flower2, Hand, ImagePlus, Play, ScanFace, Scissors, Sparkles, Upload, Volume2, VolumeX } from "lucide-react";
import { Advisor, Brand } from "@/components/Brand";
import { consultQuestions, selfQuestions, services } from "@/lib/catalog";
import { demoTenant } from "@/lib/tenant";
import { generateBeautySimulation } from "@/lib/simulation/service";

type Step="welcome"|"intent"|"services"|"path"|"wizard"|"recommend"|"summary"|"upload"|"loading"|"result";
const icons={sparkles:Sparkles,scissors:Scissors,"scan-face":ScanFace,eye:Eye,flower:Flower2,hand:Hand};
const stepProgress: Record<Step, number> = { welcome:0, intent:15, services:28, path:40, wizard:48, recommend:76, summary:80, upload:90, loading:96, result:100 };
export default function Home(){
 const [step,setStep]=useState<Step>("welcome"),[history,setHistory]=useState<Step[]>([]),[intent,setIntent]=useState(""),[service,setService]=useState(""),[path,setPath]=useState<"consult"|"self">("self"),[q,setQ]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[image,setImage]=useState(""),[muted,setMuted]=useState(true),[leadOpen,setLeadOpen]=useState(false),[submitted,setSubmitted]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const go=(next:Step)=>{setHistory(h=>[...h,step]);setStep(next)}; const back=()=>{const x=[...history];const prev=x.pop();if(prev){setHistory(x);setStep(prev)}};
 const questions=path==="consult"?consultQuestions:(selfQuestions[service]||selfQuestions.nails); const selected=services.find(s=>s.id===service);
 const progress=useMemo(()=>step==="wizard"?stepProgress.wizard+(q/questions.length)*25:stepProgress[step],[step,q,questions.length]);
 useEffect(()=>{const root=document.documentElement;Object.entries(demoTenant.theme).forEach(([k,v])=>root.style.setProperty(`--${k}`,v))},[]);
 const choose=(value:string)=>{const question=questions[q];setAnswers(a=>({...a,[question.id]:value}));if(q<questions.length-1)setQ(q+1);else go(path==="consult"?"recommend":"summary")};
 const create=async()=>{go("loading");await generateBeautySimulation({userImage:image,serviceCategory:service,selections:answers});setStep("result")};
 const upload=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)};
 if(step==="welcome")return <main className="welcome shell"><Brand/><section className="welcome-grid"><div className="video-card"><div className="video-poster"><div className="portrait"><span>م</span></div><button className="play" aria-label="پخش ویدئوی معرفی"><Play fill="currentColor"/></button><div className="video-controls"><button onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Volume2/>}</button><span>ویدئوی معرفی · ۱۰ ثانیه</span><button onClick={()=>go("intent")}>رد کردن</button></div></div><div className="video-caption"><b>{demoTenant.consultant.name}</b><span>|</span><span>{demoTenant.consultant.title}</span></div></div><div className="welcome-copy"><span className="eyebrow">قبل از تغییر، خودت را ببین</span><h1>سلام، من {demoTenant.consultant.name} هستم.<br/>خوش اومدی.</h1><p>{demoTenant.consultant.welcomeMessage}</p><button className="primary" onClick={()=>go("intent")}>شروع کنیم <ChevronLeft/></button><button className="text-button" onClick={()=>go("intent")}>بدون ویدئو ادامه بده</button></div></section></main>;
 return <main className="app-shell"><Brand/><div className="topbar"><button className="back" onClick={back} disabled={!history.length}><ArrowRight/> برگشت</button><span>{selected?.title||"شروع تجربه"}</span></div><div className="progress"><i style={{width:`${progress}%`}}/></div><section className="stage">
 {step==="intent"&&<><Advisor>امروز بیشتر دنبال تغییری یا فقط می‌خوای ببینی چه چیزی بهت میاد؟</Advisor><OptionList items={["دنبال یک تغییر جدی‌ام","فقط می‌خوام امتحان کنم","هنوز مطمئن نیستم"]} onPick={v=>{setIntent(v);go("services")}}/></>}
 {step==="services"&&<><div className="heading"><span>قدم اول</span><h1>دوست داری چی رو امتحان کنی؟</h1><p>هر زمان خواستی می‌تونی برگردی و لاین دیگه‌ای رو ببینی.</p></div><div className="service-grid">{services.map(s=>{const Icon=icons[s.icon as keyof typeof icons];return <button key={s.id} className="service-card" onClick={()=>{setService(s.id);go("path")}}><i><Icon/></i><div><b>{s.title}</b><p>{s.description}</p></div><ChevronLeft/></button>})}</div></>}
 {step==="path"&&<><Advisor>دوست داری بر اساس ویژگی‌های خودت بهت پیشنهاد بدم، یا خودت می‌خوای انتخاب کنی؟</Advisor><div className="path-grid"><button className="path-card featured" onClick={()=>{setPath("consult");setQ(0);setAnswers({});go("wizard")}}><Sparkles/><b>به من پیشنهاد بده</b><span>با چند سؤال کوتاه، گزینه‌های هماهنگ با خودت رو پیدا می‌کنیم.</span><em>پیشنهاد {demoTenant.consultant.name}</em></button><button className="path-card" onClick={()=>{setPath("self");setQ(0);setAnswers({});go("wizard")}}><Hand/><b>خودم انتخاب می‌کنم</b><span>قدم‌به‌قدم بین مدل‌ها و استایل‌ها انتخاب کن.</span></button></div></>}
 {step==="wizard"&&<><Advisor>{q===0&&path==="consult"?"اول یه کم بیشتر بشناسمت تا بتونم دقیق‌تر پیشنهاد بدم.":questions[q].question}</Advisor>{q===0&&path==="consult"&&<h2 className="question-repeat">{questions[q].question}</h2>}{questions[q].hint&&<p className="hint">{questions[q].hint}</p>}<span className="counter">سؤال {q+1} از {questions.length}</span><OptionList items={questions[q].options} selected={answers[questions[q].id]} onPick={choose}/></>}
 {step==="recommend"&&<><Advisor>خب، با چیزهایی که ازت فهمیدم، فکر می‌کنم این سه مدل ارزش امتحان کردن دارن.</Advisor><div className="recommendations">{["کاراملی گرم","بژ عسلی","بالیاژ برزیلی ملایم"].map((x,i)=><button key={x} onClick={()=>{setAnswers(a=>({...a,recommendation:x}));go("summary")}}><span>۰{i+1}</span><div><b>{x}</b><p>{i===0?"گرم، روشن و طبیعی؛ با نگهداری ساده‌تر.":i===1?"درخشش ملایم و چهره‌ای نرم‌تر.":"تغییری ظریف با عمق بیشتر در مو."}</p></div><ChevronLeft/></button>)}</div><p className="disclaimer">این‌ها پیشنهادهای اولیه‌ان؛ انتخاب نهایی همیشه با توئه.</p></>}
 {step==="summary"&&<><div className="heading"><span>همه‌چیز آماده‌ست</span><h1>انتخاب تو</h1></div><div className="summary-card"><div className="summary-icon"><Sparkles/></div><h2>{selected?.title}</h2>{Object.values(answers).map(v=><p key={v}><Check/> {v}</p>)}</div><button className="primary" onClick={()=>go("upload")}>تأیید و شبیه‌سازی <ChevronLeft/></button><button className="secondary" onClick={()=>{setQ(0);go("wizard")}}>ویرایش انتخاب‌ها</button></>}
 {step==="upload"&&<><Advisor>برای اینکه نتیجه تا حد ممکن شبیه خودت باشه، یه عکس واضح از روبه‌رو برام بفرست.</Advisor><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0])}/><button className={`dropzone ${image?"has-image":""}`} onClick={()=>fileRef.current?.click()}>{image?<img src={image} alt="پیش‌نمایش عکس انتخاب‌شده"/>:<><span><ImagePlus/></span><b>عکست رو اینجا اضافه کن</b><small>JPG یا PNG · حداکثر ۱۰ مگابایت</small><em><Upload/> انتخاب عکس</em></>}</button><div className="photo-tips"><div className="photo-example good"><ScanFace/><b><Check/> عکس مناسب</b><small>روبه‌رو، نور طبیعی، چهره واضح</small></div><div className="photo-example bad"><ScanFace/><b>× نامناسب</b><small>تار، خیلی دور یا با فیلتر سنگین</small></div></div><label className="privacy"><input type="checkbox"/> <span>می‌خوام این عکس در حسابم نگهداری بشه.</span></label><p className="privacy-note">عکس فقط برای ساخت شبیه‌سازی استفاده می‌شه و بدون اجازه تو برای هدف دیگه‌ای استفاده نمی‌شه.</p><button disabled={!image} className="primary" onClick={create}>ساخت شبیه‌سازی <Sparkles/></button></>}
 {step==="loading"&&<div className="loading"><div className="skeleton"><Sparkles/></div><h1>داریم انتخابت رو روی چهره خودت می‌سازیم…</h1><p>جزئیات رو داریم دقیق‌تر می‌کنیم…</p><div className="loading-line"><i/></div></div>}
 {step==="result"&&<><div className="heading center"><span>نتیجه آماده‌ست</span><h1>این هم انتخاب تو، روی خودت</h1></div><div className="result-image"><img src={image} alt="نتیجه شبیه‌سازی آزمایشی"/><span><Sparkles/> پیش‌نمایش آزمایشی</span></div><Advisor>این انتخاب، چهره‌ت رو گرم‌تر و روشن‌تر نشون می‌ده و در عین حال طبیعی مونده.</Advisor><div className="result-actions"><button className="primary" onClick={()=>setLeadOpen(true)}>یه مدل دیگه امتحان کنم</button><button className="secondary" onClick={()=>setLeadOpen(true)}>مشاوره تخصصی می‌خوام</button><button className="text-button" onClick={()=>alert("نتیجه برای دانلود آماده شد.")}>ذخیره نتیجه</button></div><div className="unlock"><b>دو انتخاب دیگه هم امتحان کن</b><p>با گذاشتن راه ارتباطی، دو شبیه‌سازی دیگه برات فعال می‌شه.</p><button onClick={()=>setLeadOpen(true)}>فعال کردن دو نتیجه رایگان <ChevronLeft/></button></div>{leadOpen&&<LeadModal done={submitted} close={()=>setLeadOpen(false)} submit={()=>setSubmitted(true)}/>}</>}
 </section><footer>ساخته‌شده برای تجربه‌ای امن و آگاهانه · {demoTenant.salonName}</footer></main>
}
function OptionList({items,onPick,selected}:{items:string[];onPick:(v:string)=>void;selected?:string}){return <div className="options">{items.map((x,i)=><button className={selected===x?"selected":""} key={x} onClick={()=>onPick(x)}><span>{String(i+1).padStart(2,"۰")}</span><b>{x}</b><i>{selected===x?<Check/>:<ChevronLeft/>}</i></button>)}</div>}
function LeadModal({close,submit,done}:{close:()=>void;submit:()=>void;done:boolean}){return <div className="modal-backdrop"><div className="modal">{done?<div className="success"><span><Check/></span><h2>درخواستت ثبت شد</h2><p>مشاور زیبایی برای بررسی دقیق‌تر نتیجه باهات هماهنگ می‌شه.</p><button className="primary" onClick={close}>خیلی هم عالی</button></div>:<><button className="modal-close" onClick={close}>×</button><span className="eyebrow">ارتباط با مشاور</span><h2>چطور باهات در تماس باشیم؟</h2><p>اطلاعاتت فقط برای پیگیری همین مشاوره استفاده می‌شه.</p><label>نام<input placeholder="مثلاً سارا"/></label><label>شماره موبایل<input inputMode="tel" placeholder="۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label><label>واتس‌اپ یا تلگرام <small>اختیاری</small><input placeholder="آیدی یا شماره"/></label><button className="primary" onClick={submit}>ثبت درخواست</button></>}</div></div>}
