"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Camera, Check, ChevronLeft, Eye, Flower2, Hand, Heart, Image as ImageIcon, Images, ScanFace, Scissors, Sparkles, Upload, Volume2, VolumeX, WandSparkles } from "lucide-react";
import { Brand } from "@/components/Brand";
import { MirrorButton, MirrorCard, MirrorFrame, MirrorGlow, MirrorIcon, MirrorModal, MirrorProgress, MirrorTile } from "@/components/mirror/MirrorUI";
import { getOption, services } from "@/lib/catalog";
import { demoTenant } from "@/lib/tenant";
import { ImageAsset, PhotoType, RecommendationMode } from "@/lib/types";
import { generateBeautySimulation } from "@/lib/simulation/service";

type Step="welcome"|"photo"|"paths"|"recommend"|"services"|"requirement"|"detail"|"wizard"|"loading"|"result"|"portfolio";
const icons={sparkles:Sparkles,scissors:Scissors,"scan-face":ScanFace,eye:Eye,flower:Flower2,hand:Hand,heart:Heart,wand:WandSparkles};
const recs:{id:RecommendationMode;nameFa:string;nameEn:string;copy:string}[]=[{id:"natural",nameFa:"نسخه طبیعی من",nameEn:"Natural Me",copy:"تغییری ظریف، هماهنگ و کم‌ریسک"},{id:"signature",nameFa:"امضای من",nameEn:"Signature Me",copy:"استایلی که می‌تونه امضای تصویری تو باشه"},{id:"bold",nameFa:"نسخه جسورانه من",nameEn:"Bold Me",copy:"تغییری چشمگیر، اما همچنان هماهنگ با تو"}];
export default function Home(){
 const [step,setStep]=useState<Step>("welcome"),[history,setHistory]=useState<Step[]>([]),[videoDone,setVideoDone]=useState(false),[muted,setMuted]=useState(true),[videoError,setVideoError]=useState(false),[primaryImages,setPrimaryImages]=useState<Partial<Record<"face"|"hand",ImageAsset>>>({}),[detailImages,setDetailImages]=useState<ImageAsset[]>([]),[consent,setConsent]=useState(false),[serviceId,setServiceId]=useState(""),[decision,setDecision]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[mode,setMode]=useState<RecommendationMode>(),[leadOpen,setLeadOpen]=useState(false),[leadDone,setLeadDone]=useState(false),[slider,setSlider]=useState(50),[generationCount,setGenerationCount]=useState(0); const galleryRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null); const inputRole=useRef<{type:PhotoType;source:"camera"|"gallery"}>({type:"face",source:"gallery"});
 const service=services.find(s=>s.id===serviceId),current=service?.decisions[decision],requirement=service?.photoRequirements,detailType=requirement?.detailTypes[0];
 const progress=useMemo(()=>({welcome:0,photo:18,paths:35,recommend:55,services:48,requirement:57,detail:61,wizard:70,loading:90,result:100,portfolio:30}[step]),[step]);
 const go=(s:Step)=>{setHistory(h=>[...h,step]);setStep(s)},back=()=>{const h=[...history];let s=h.pop();while(s==="loading")s=h.pop();if(s){setHistory(h);setStep(s)}};
 const openFile=(type:PhotoType,source:"camera"|"gallery")=>{inputRole.current={type,source};(source==="camera"?cameraRef:galleryRef).current?.click()};
 const file=(f?:File)=>{if(!f)return;const {type,source}=inputRole.current,reader=new FileReader();reader.onload=()=>{const asset:ImageAsset={id:`${type}-${Date.now()}`,type,dataUrl:String(reader.result),source,role:type==="face"||type==="hand"?"primary":"detail"};if(asset.role==="primary")setPrimaryImages(x=>({...x,[type]:asset}));else setDetailImages(x=>[...x.filter(i=>i.type!==type),asset]);if(step==="photo")go("paths");else if(step==="requirement")detailType?go("detail"):go("wizard");else go("wizard")};reader.readAsDataURL(f)};
 const chooseService=(id:string)=>{const chosen=services.find(s=>s.id===id)!;setServiceId(id);setDecision(0);setAnswers({});if(!primaryImages[chosen.photoRequirements.primaryType])go("requirement");else if(chosen.photoRequirements.optionalDetailImages)go("detail");else go("wizard")};
 const selectOption=(id:string)=>{if(!current)return;const next={...answers,[current.id]:id};setAnswers(next);if(service&&decision<service.decisions.length-1)setDecision(x=>x+1);else create(next)};
 const create=async(next=answers,nextMode=mode)=>{const primary=service?primaryImages[service.photoRequirements.primaryType]:primaryImages.face;if(!primary)return;go("loading");await generateBeautySimulation({images:{primaryImage:primary,detailImages,referenceImages:[]},tenantId:demoTenant.id,serviceCategory:serviceId||"recommendation",selectedOptions:next,selectedReferences:Object.entries(next).map(([k,v])=>getOption(serviceId,k,v)?.referenceId).filter(Boolean) as string[],recommendationMode:nextMode,identityPreservationInstructions:service?.photoRequirements.identityPreservationRules});setGenerationCount(x=>x+1);setStep("result")};
 useEffect(()=>{Object.entries(demoTenant.theme).forEach(([k,v])=>document.documentElement.style.setProperty(`--${k}`,v))},[]);
 const inputs=<><input ref={cameraRef} hidden type="file" accept="image/*" capture="user" onChange={e=>file(e.target.files?.[0])}/><input ref={galleryRef} hidden type="file" accept="image/*" onChange={e=>file(e.target.files?.[0])}/></>;
 if(step==="welcome")return <main className="welcome"><MirrorGlow/><Brand/><section className={`welcome-scene ${videoDone?"revealed":"speaking"}`}><div className="assistant-presence"><video autoPlay muted={muted} playsInline preload="metadata" poster={demoTenant.consultant.posterUrl} src={demoTenant.consultant.videoUrl} onEnded={()=>setVideoDone(true)} onError={()=>{setVideoError(true);setVideoDone(true)}}/>{videoError&&<div className="video-fallback"><MirrorIcon/><span>MARVAA</span></div>}<div className="presence-vignette"/><div className="assistant-id"><b>MARVAA</b><small dir="ltr">Beauty AI Concierge</small></div><div className="video-actions"><button onClick={()=>setMuted(x=>!x)} aria-label={muted?"روشن کردن صدا":"بی‌صدا کردن"}>{muted?<VolumeX/>:<Volume2/>}</button><button onClick={()=>setVideoDone(true)}>رد کردن</button></div></div><div className="welcome-reveal"><div className="signature-mirror"><span>✦</span></div><p className="kicker">FUTURE MIRROR · آینه مروا</p><h1 className="text-hero">خودت، اما متفاوت ✦</h1><MirrorButton onClick={()=>go("photo")}>بزن بریم</MirrorButton></div></section></main>;
 return <main className="app-shell"><MirrorGlow/><header className="flow-header"><button className="back" onClick={back}><ArrowRight/> برگشت</button><Brand/><button className="portfolio-link" onClick={()=>go("portfolio")}><Images/> امضای مروا</button></header><MirrorProgress value={progress}/><section className="stage">{inputs}
 {step==="photo"&&<><Heading eyebrow="اولین نگاه" title="اگر دوست داری، اول خودت رو به آینه نشون بده." text="عکس چهره برای تجربه‌های صورت و مو استفاده می‌شه؛ می‌تونی فعلاً فقط سرویس‌ها رو ببینی."/><PhotoMirror type="face" guidance={services[0].photoRequirements.guidance.map(x=>x.nameFa)} camera={()=>openFile("face","camera")} gallery={()=>openFile("face","gallery")}/><MirrorButton variant="ghost" onClick={()=>go("services")}>فعلاً بدون عکس ادامه می‌دم</MirrorButton><Consent checked={consent} set={setConsent}/></>}
 {step==="paths"&&<><Heading eyebrow="آینه باز شد" title="این بار، انتخاب با توئه." text="می‌خوای مروا جهت رو پیشنهاد بده یا خودت همه جزئیات رو بسازی؟"/><div className="major-paths"><MirrorTile nameFa="مروا برام انتخاب کنه" nameEn="Let Marvaa Choose" icon={<Sparkles/>} onClick={()=>go("recommend")}/><MirrorTile nameFa="خودم استایلم رو می‌سازم" nameEn="Build My Own Style" icon={<Hand/>} onClick={()=>go("services")}/></div></>}
 {step==="recommend"&&<><Heading eyebrow="سه انعکاس از تو" title="دوست داری کدوم نسخه رو ببینی؟" text="هر سه حالت، هویت و ویژگی‌های واقعی چهره‌ت رو حفظ می‌کنن."/><div className="recommend-states">{recs.map((r,i)=><button key={r.id} onClick={()=>{setMode(r.id);create({},r.id)}}><span>۰{i+1}</span><div><b>{r.nameFa}</b><small dir="ltr">{r.nameEn}</small><p>{r.copy}</p></div><i>✦</i></button>)}</div></>}
 {step==="services"&&<><Heading eyebrow="استایل خودت" title="از کجا شروع کنیم؟" text="هر سرویس عکس مناسب خودش رو می‌شناسه؛ هر بار فقط یک تصمیم."/><div className="service-grid">{services.map(s=>{const Icon=icons[s.icon as keyof typeof icons]||Sparkles;return <MirrorTile key={s.id} nameFa={s.nameFa} nameEn={s.nameEn} icon={<Icon/>} onClick={()=>chooseService(s.id)}/>})}</div></>}
 {step==="requirement"&&requirement&&<><Heading eyebrow={requirement.primaryType==="hand"?"عکس دست · Hand photo":"عکس چهره · Face photo"} title={requirement.primaryType==="hand"?"برای دیدن مدل ناخن روی دست خودت، یه عکس واضح از دستت لازم دارم.":"برای دیدن این تغییر روی خودت، یه عکس واضح از چهره‌ت لازم دارم."} text={requirement.primaryType==="face"&&["hair-color","haircut","updo"].includes(serviceId)?"موها هم تا جای ممکن کامل و واضح داخل کادر باشن.":"این تصویر، عکس اصلی نتیجه نهایی خواهد بود."}/><PhotoMirror type={requirement.primaryType} guidance={requirement.guidance.map(x=>x.nameFa)} camera={()=>openFile(requirement.primaryType,"camera")} gallery={()=>openFile(requirement.primaryType,"gallery")}/></>}
 {step==="detail"&&detailType&&<><Heading eyebrow="جزئیات اختیاری · Optional detail" title={detailCopy(detailType)} text="نتیجه نهایی همچنان بر پایه عکس کامل چهره‌ت ساخته می‌شه؛ این عکس فقط مرجع جزئیاته."/><PhotoMirror type={detailType} guidance={["نمای نزدیک و واضح","نور مناسب","بدون فیلتر"]} camera={()=>openFile(detailType,"camera")} gallery={()=>openFile(detailType,"gallery")} detail/><MirrorButton variant="ghost" onClick={()=>go("wizard")}>رد کردن</MirrorButton></>}
 {step==="wizard"&&current&&<><Heading eyebrow={`${service?.nameFa} · ${decision+1} از ${service?.decisions.length}`} title={current.questionFa} text="کدومش بیشتر به چیزی که تو ذهنت هست نزدیکه؟"/><div className="option-groups">{current.groups.map(g=><section key={g.id}><h2>{g.nameFa}<small dir="ltr">{g.nameEn}</small></h2><div className="options">{g.options.filter(o=>o.active).map(x=><MirrorTile key={x.id} nameFa={x.nameFa} nameEn={x.nameEn} selected={answers[current.id]===x.id} onClick={()=>selectOption(x.id)}/>)}</div></section>)}</div></>}
 {step==="loading"&&<div className="mirror-loading"><div className="loading-mirror"><span>✦</span></div><h1>چند لحظه تا دیدنِ متفاوتِ خودت… ✦</h1><p>داریم جزئیات رو دقیق می‌کنیم</p></div>}
 {step==="result"&&<Result image={(service?primaryImages[service.photoRequirements.primaryType]:primaryImages.face)?.dataUrl||""} slider={slider} setSlider={setSlider} generationCount={generationCount} leadDone={leadDone} another={()=>generationCount>=demoTenant.limits.anonymous&&!leadDone?setLeadOpen(true):go("paths")} lead={()=>setLeadOpen(true)}/> }
 {step==="portfolio"&&<Portfolio/>}{leadOpen&&<LeadModal done={leadDone} close={()=>setLeadOpen(false)} submit={()=>setLeadDone(true)}/>}</section><footer>{demoTenant.salonName} · تجربه‌ای امن، خصوصی و هوشمند</footer></main>
}
function detailCopy(t:PhotoType){return t==="brows-closeup"?"برای اینکه فرم و جزئیات ابرو دقیق‌تر دربیاد، یه عکس نزدیک از ابروهات هم بفرست.":t==="eyes-closeup"?"برای نتیجه دقیق‌تر، یه عکس نزدیک و واضح از چشم‌ها و مژه‌هات بفرست.":"برای جزئیات دقیق‌تر شیدینگ، می‌تونی یه عکس نزدیک از لب‌هات بفرستی."}
function PhotoMirror({type,guidance,camera,gallery,detail=false}:{type:PhotoType;guidance:string[];camera:()=>void;gallery:()=>void;detail?:boolean}){return <MirrorFrame className="capture"><MirrorIcon>{type==="hand"?<Hand/>:<ScanFace/>}</MirrorIcon><div className="tips">{guidance.map(x=><span key={x}>{x}</span>)}</div><MirrorButton onClick={camera}><Camera/> {detail?"گرفتن عکس نزدیک":type==="hand"?"همین الان عکس دست بگیر":"همین الان عکس بگیر"}</MirrorButton><MirrorButton variant="secondary" onClick={gallery}><Upload/> از گالری انتخاب کن</MirrorButton></MirrorFrame>}
function Consent({checked,set}:{checked:boolean;set:(x:boolean)=>void}){return <><label className="consent"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><span><b>اجازه ذخیره دائمی عکس</b><small>اختیاری — بدون این اجازه عکس فقط در همین تجربه استفاده می‌شه.</small></span></label><p className="privacy">عکس فقط برای ساخت شبیه‌سازی استفاده می‌شه و بدون اجازه تو برای هدف دیگه‌ای استفاده نمی‌شه.</p></>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="heading"><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Result({image,slider,setSlider,generationCount,leadDone,another,lead}:{image:string;slider:number;setSlider:(x:number)=>void;generationCount:number;leadDone:boolean;another:()=>void;lead:()=>void}){return <><Heading eyebrow="آینه آماده‌ست" title="این هنوز خودتی." text="خط روی تصویر رو بکش و قبل و بعد رو با هم ببین."/><MirrorFrame className="comparison"><img src={image} alt="من الان"/><div className="after" style={{clipPath:`inset(0 0 0 ${slider}%)`}}><img src={image} alt="نسخه جدید من"/><div className="mock-effect"/></div><input aria-label="مقایسه قبل و بعد" type="range" min="0" max="100" value={slider} onChange={e=>setSlider(Number(e.target.value))}/><div className="divider" style={{left:`${slider}%`}}/><span className="before-label">من الان</span><span className="after-label">نسخه جدید من</span></MirrorFrame><div className="result-actions"><MirrorButton onClick={another}>یه نسخه دیگه ببینم</MirrorButton><MirrorButton variant="secondary">این استایل رو دوست دارم</MirrorButton><MirrorButton variant="ghost" onClick={lead}>مشاوره با مروا</MirrorButton></div><BeautyPassport/>{generationCount===1&&!leadDone&&<MirrorCard className="unlock"><b>دوست داری دو نسخه دیگه از خودت رو هم ببینی؟</b><p>راه ارتباطی‌ت رو بذار تا {demoTenant.limits.extraAfterLead} آینه دیگه باز بشه.</p><button onClick={lead}>باز کردن نسخه‌ها <ChevronLeft/></button></MirrorCard>}</>}
function BeautyPassport(){return <MirrorCard className="passport"><span>MARVAA BEAUTY ID</span><h2>پاسپورت زیبایی تو</h2><div><i>تناژ ترجیحی<small>در حال شناختن</small></i><i>شدت محبوب<small>متعادل</small></i><i>استایل‌های دوست‌داشتنی<small>۱ مورد</small></i></div></MirrorCard>}
function Portfolio(){const [cat,setCat]=useState(services[0].id);return <><Heading eyebrow="کارهای واقعی سالن" title="امضای مروا" text="این گالری از کتابخانه مرجع و شبیه‌سازی هوش مصنوعی کاملاً جداست."/><div className="portfolio-filters">{services.map(s=><button className={cat===s.id?"active":""} onClick={()=>setCat(s.id)} key={s.id}><b>{s.nameFa}</b><small dir="ltr">{s.nameEn}</small></button>)}</div><div className="portfolio-showcase"><MirrorFrame><div className="portfolio-placeholder"><ImageIcon/><span>نمونه‌های واقعی {services.find(s=>s.id===cat)?.nameFa}</span><small>از پنل مدیریت قابل بارگذاری و مرتب‌سازی</small></div></MirrorFrame></div></>}
function LeadModal({close,submit,done}:{close:()=>void;submit:()=>void;done:boolean}){return <MirrorModal onClose={close}>{done?<div className="success"><MirrorIcon><Check/></MirrorIcon><h2>دو آینه دیگه برات باز شد</h2><p>حالا می‌تونی دو نسخه تازه هم ببینی.</p><MirrorButton onClick={close}>ادامه می‌دم</MirrorButton></div>:<><span className="kicker">دو نسخه بیشتر</span><h2>چطور باهات در تماس باشیم؟</h2><p className="muted">اطلاعاتت فقط برای همین تجربه و پیگیری مشاوره استفاده می‌شه.</p><label>نام<input required placeholder="مثلاً سارا"/></label><label>شماره موبایل<input required inputMode="tel" placeholder="۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label><label>واتس‌اپ <small>اختیاری</small><input inputMode="tel"/></label><label>تلگرام <small>اختیاری</small><input dir="ltr"/></label><MirrorButton onClick={submit}>باز کردن دو نسخه</MirrorButton></>}</MirrorModal>}
