import { Decision, PhotoRequirement, Service, StyleOption } from "./types";
const o=(id:string,nameFa:string,nameEn:string,group?:string):StyleOption=>({id,nameFa,nameEn,group,active:true,sortOrder:0,referenceId:`ref-${id}`,promptFragment:`Apply the distinct ${nameEn} style exactly as shown by its references.`,generationRules:["Modify only the selected service area","Preserve identity and unselected features"]});
const d=(id:string,nameFa:string,nameEn:string,questionFa:string,options:StyleOption[],groups?:{id:string;nameFa:string;nameEn:string;options:StyleOption[]}[]):Decision=>({id,nameFa,nameEn,questionFa,questionEn:nameEn,groups:groups||[{id, nameFa,nameEn,options}]});
const faceGuidance=[{id:"light",nameFa:"نور مناسب",nameEn:"Good light"},{id:"clear",nameFa:"صورت واضح",nameEn:"Clear face"},{id:"no-filter",nameFa:"بدون فیلتر",nameEn:"No filter"},{id:"front",nameFa:"چهره روبه‌رو",nameEn:"Front-facing"}];
const face=(detailTypes:PhotoRequirement["detailTypes"]=[]):PhotoRequirement=>({primaryType:"face",required:true,detailTypes,guidance:faceGuidance,optionalDetailImages:detailTypes.length>0,identityPreservationRules:["Preserve full facial identity","Keep the final output as a full-face image","Change only the selected service area"]});
const hand:PhotoRequirement={primaryType:"hand",required:true,detailTypes:[],optionalDetailImages:false,guidance:[{id:"whole-hand",nameFa:"دست کامل داخل کادر",nameEn:"Full hand in frame"},{id:"nails-clear",nameFa:"ناخن‌ها واضح",nameEn:"Clear nails"},{id:"light",nameFa:"نور مناسب",nameEn:"Good light"},{id:"no-filter",nameFa:"بدون فیلتر",nameEn:"No filter"},{id:"top",nameFa:"ترجیحاً دست از بالا دیده شود",nameEn:"Preferably from above"}],identityPreservationRules:["Analyze nail position","Preserve hand identity, fingers, skin, and jewelry","Change only nail shape and color"]};
const shades=[
 {id:"cool",nameFa:"رنگساژ سرد",nameEn:"Cool Toners",options:[o("icy","یخی","Icy","cool"),o("smoky","دودی","Ash","cool"),o("oyster","صدفی","Pearlescent Oyster","cool"),o("silver","نقره‌ای","Silver","cool"),o("pearl","مرواریدی","Pearl","cool"),o("cool-beige","بژ سرد","Cool Beige","cool"),o("cool-caramel","کاراملی سرد","Cool Caramel","cool")]},
 {id:"warm",nameFa:"رنگساژ گرم",nameEn:"Warm Toners",options:[o("chocolate-warm","شکلاتی","Chocolate","warm"),o("warm-caramel","کاراملی","Warm Caramel","warm"),o("mocha-warm","موکا","Mocha","warm"),o("honey","عسلی","Honey","warm"),o("copper-warm","مسی","Copper","warm"),o("rose-gold","رزگلد","Rose Gold","warm"),o("champagne","شامپاینی","Champagne","warm"),o("golden-cream","کرم طلایی","Golden Cream","warm")]},
 {id:"fantasy",nameFa:"رنگ فانتزی",nameEn:"Fantasy Colors",options:[["blue","آبی","Blue"],["red","قرمز","Red"],["orange","نارنجی","Orange"],["purple","بنفش","Purple"],["yellow","زرد","Yellow"]].map(x=>o(x[0],x[1],x[2],"fantasy"))},
 {id:"natural",nameFa:"رنگ موی طبیعی",nameEn:"Natural Hair Colors",options:[["chocolate-natural","شکلاتی","Chocolate"],["mocha-natural","موکا","Mocha"],["nescafe","نسکافه‌ای","Nescafé Brown"],["burgundy","شرابی","Burgundy"],["black","مشکی","Black"],["copper-natural","مسی","Copper"],["chestnut","خرمایی","Chestnut"],["ash-brown","قهوه‌ای دودی","Ash Brown"]].map(x=>o(x[0],x[1],x[2],"natural"))}
];
const servicesData:Service[]=[
 {id:"hair-color",photoRequirements:face(),nameFa:"رنگ مو",nameEn:"Hair Color",description:"تکنیک و تناژ رو مستقل و دقیق انتخاب کن.",icon:"sparkles",enabled:true,sortOrder:1,decisions:[d("technique","تکنیک رنگ","Color Technique","دوست داری رنگ چطور روی موهات بنشینه؟",[["all-over-color","رنگ یکدست","All-over Color"],["full-bleach","دکلره کامل","Full Bleach"],["balayage","بالیاژ","Balayage"],["ombre","آمبره","Ombre"],["sombre","سامبره","Sombré"],["highlights","هایلایت","Highlights"],["cap-highlights","مش کلاهی","Cap Highlights"]].map(x=>o(x[0],x[1],x[2]))),d("shade","انتخاب تناژ","Choose a Shade","کدوم تناژ بیشتر شبیه چیزی‌ست که توی ذهنت داری؟",[],shades)]},
 {id:"haircut",photoRequirements:face(),nameFa:"کوتاهی مو",nameEn:"Haircut",description:"فرم تازه‌ی مو رو قبل از قیچی ببین.",icon:"scissors",enabled:true,sortOrder:2,decisions:[d("cut","مدل کوتاهی","Haircut Style","کدوم فرم بیشتر به خودت نزدیکه؟",[],[{id:"bob",nameFa:"باب",nameEn:"Bob",options:[o("graduated-bob","گرجوئیشن","Graduated Bob"),o("angled-bob","شیب‌دار","Angled Bob")]},{id:"layer",nameFa:"لیر",nameEn:"Layers",options:[o("long-layers","بلند","Long Layers"),o("shaggy","شگی","Shag"),o("wolf-cut","ولف‌کات","Wolf Cut"),o("butterfly","پروانه‌ای","Butterfly Cut")]},{id:"pixie",nameFa:"پیکسی",nameEn:"Pixie",options:[o("pixie","پیکسی","Pixie Cut")]},{id:"bangs",nameFa:"کوتاهی چتری",nameEn:"Bangs",options:[o("blunt-bangs","چتری صاف","Blunt Bangs"),o("curtain-bangs","چتری پرده‌ای","Curtain Bangs")]}])]},
 {id:"lashes",photoRequirements:face(["eyes-closeup"]),nameFa:"مژه",nameEn:"Lashes",description:"حالت و حجم مناسب چشم‌هات.",icon:"eye",enabled:true,sortOrder:3,decisions:[d("lash","استایل مژه","Lash Style","چه حالتی برای مژه‌هات دوست داری؟",[["classic","کلاسیک","Classic"],["hybrid","هیبرید","Hybrid"],["volume","والیوم","Volume"],["wispy","ویسپی","Wispy"],["spiky","اسپایکی","Spiky"],["mega-volume","مگا والیوم","Mega Volume"]].map(x=>o(x[0],x[1],x[2])))]},
 {id:"brows",photoRequirements:face(["brows-closeup"]),nameFa:"ابرو",nameEn:"Brows",description:"تکنیک‌های مستقل و طبیعی ابرو.",icon:"scan-face",enabled:true,sortOrder:4,decisions:[d("brow","استایل ابرو","Brow Style","کدوم نتیجه به سلیقه‌ت نزدیک‌تره؟",[["microblading","میکروبلیدینگ / هاشور مویی","Microblading / Hair Strokes"],["nano-brows","نانو بروز / هاشور مویی با دستگاه","Nano Brows / Machine Strokes"],["powder-brows","پودری / شیدینگ","Powder Brows / Shading"],["ombre-brows","آمبره بروز","Ombre Brows"],["combo-brows","کامبو / ترکیبی","Combo Brows"]].map(x=>o(x[0],x[1],x[2])))]},
 {id:"lips",photoRequirements:face(["lips-closeup"]),nameFa:"لب",nameEn:"Lips",description:"رنگ ملایم و تعریف طبیعی لب.",icon:"heart",enabled:true,sortOrder:5,decisions:[d("lip","استایل لب","Lip Style","برای لب از اینجا شروع کنیم.",[o("lip-blush","شیدینگ لب","Lip Blush")])]},
 {id:"nails",photoRequirements:hand,nameFa:"ناخن",nameEn:"Nails",description:"اول فرم، بعد رنگ مورد علاقه‌ت.",icon:"hand",enabled:true,sortOrder:6,decisions:[d("shape","فرم ناخن","Nail Shape","چه فرمی برای ناخن‌هات می‌پسندی؟",[["natural-nail","طبیعی","Natural"],["square","مربعی","Square"],["almond","بادامی","Almond"],["mindal","میندال","Mindal"]].map(x=>o(x[0],x[1],x[2]))),d("nail-color","رنگ ناخن","Nail Color","حالا کدوم رنگ توی آینه بدرخشه؟",[["green","سبز","Green"],["blue-nail","آبی","Blue"],["butter-yellow","زرد کره‌ای","Butter Yellow"],["black-nail","مشکی","Black"],["pearl-nail","صدفی","Pearl"],["pink","صورتی","Pink"],["red-nail","قرمز","Red"],["brown","قهوه‌ای","Brown"],["orange-nail","نارنجی","Orange"],["navy","سورمه‌ای","Navy"],["bubblegum","آدامسی","Bubblegum Pink"],["bronze","برنز","Bronze"],["silver-nail","نقره‌ای","Silver"],["gold","طلایی","Gold"]].map(x=>o(x[0],x[1],x[2])))]},
 {id:"makeup",photoRequirements:face(),nameFa:"میکاپ",nameEn:"Makeup",description:"شدت میکاپ رو روی خودت مقایسه کن.",icon:"wand",enabled:true,sortOrder:7,decisions:[d("makeup","شدت میکاپ","Makeup Intensity","چه میزان درخشش می‌خوای؟",[["light","لایت","Light"],["medium","مدیوم","Medium"],["full-glam","فول گلام","Full Glam"]].map(x=>o(x[0],x[1],x[2])))]},
 {id:"updo",photoRequirements:face(),nameFa:"شینیون",nameEn:"Hairstyle / Updo",description:"استایل مو برای لحظه‌های خاص.",icon:"flower",enabled:true,sortOrder:8,decisions:[d("updo","حالت شینیون","Updo Style","موهات رو چطور تصور می‌کنی؟",[["open","باز","Open"],["closed","بسته","Updo"],["half-open","نیمه‌باز","Half-up"]].map(x=>o(x[0],x[1],x[2])))]}
];
export const services=servicesData.filter(x=>x.enabled).sort((a,b)=>a.sortOrder-b.sortOrder);
export const getOption=(serviceId:string,decisionId:string,optionId:string)=>services.find(s=>s.id===serviceId)?.decisions.find(d=>d.id===decisionId)?.groups.flatMap(g=>g.options).find(o=>o.id===optionId);
