"use client";
import {useEffect,useState} from "react";
import {getContext} from "@/lib/admin/data";
import {logSupabaseError,rest,signedStorageUrl} from "@/lib/supabase/client";

type Status="new"|"contacted"|"booked"|"closed";
type Lead={id:string;session_id:string|null;service_category_id:string|null;name:string|null;mobile:string|null;whatsapp:string|null;telegram:string|null;selected_options:Record<string,string>;preferred_at:string|null;created_at:string;status:Status};
type Generation={id:string;session_id:string|null;choice_id:string|null;input_path:string|null;output_path:string|null;status:string;metadata:Record<string,unknown>;created_at:string;input_url?:string;output_url?:string};
type Request={id:string;session_id:string|null;lead_id:string|null;generation_id:string|null;status:string;notes:string|null;created_at:string};
type Choice={id:string;category_id:string|null;selections:Record<string,string>;created_at:string};
type Category={id:string;name:string};
type Customer={key:string;leads:Lead[];generations:Generation[];requests:Request[]};
const requestStatuses=["new","contacted","booked","closed"];
const normalizeMobile=(value:string|null)=>value?.replace(/\D/g,"")||"";

export function LeadManager(){
 const [customers,setCustomers]=useState<Customer[]>([]),[categories,setCategories]=useState<Record<string,string>>({}),[choices,setChoices]=useState<Record<string,Choice>>({}),[busy,setBusy]=useState(true),[error,setError]=useState("");
 async function load(){try{setBusy(true);setError("");const context=await getContext();const [leads,generations,requests,choiceRows,categoryRows]=await Promise.all([
  rest<Lead[]>(`leads?select=id,session_id,service_category_id,name,mobile,whatsapp,telegram,selected_options,preferred_at,created_at,status&tenant_id=eq.${context.tenantId}&order=created_at.desc`),
  rest<Generation[]>(`image_generations?select=id,session_id,choice_id,input_path,output_path,status,metadata,created_at&tenant_id=eq.${context.tenantId}&order=created_at.desc`),
  rest<Request[]>(`contact_requests?select=id,session_id,lead_id,generation_id,status,notes,created_at&tenant_id=eq.${context.tenantId}&order=created_at.desc`),
  rest<Choice[]>(`user_choices?select=id,category_id,selections,created_at&tenant_id=eq.${context.tenantId}&order=created_at.desc`),
  rest<Array<{id:string;name_fa:string|null;title:string}>>(`service_categories?select=id,name_fa,title&tenant_id=eq.${context.tenantId}`)
 ]);setCategories(Object.fromEntries(categoryRows.map(row=>[row.id,row.name_fa||row.title])));setChoices(Object.fromEntries(choiceRows.map(row=>[row.id,row])));
 await Promise.all(generations.flatMap(g=>[["input_path","input_url"],["output_path","output_url"]].map(async([pathKey,urlKey])=>{const path=g[pathKey as "input_path"|"output_path"];if(!path)return;try{g[urlKey as "input_url"|"output_url"]=await signedStorageUrl("customer-simulations",path)}catch(e){logSupabaseError(`sign customer ${pathKey} for generation ${g.id}`,e)}})));
 const groups=new Map<string,Customer>();for(const lead of leads){const mobile=normalizeMobile(lead.mobile);const key=mobile?`mobile:${mobile}`:`lead:${lead.id}`;const group=groups.get(key)||{key,leads:[],generations:[],requests:[]};group.leads.push(lead);groups.set(key,group)}
 for(const group of groups.values()){const leadIds=new Set(group.leads.map(l=>l.id)),sessions=new Set(group.leads.map(l=>l.session_id).filter(Boolean));group.requests=requests.filter(r=>(r.lead_id&&leadIds.has(r.lead_id))||(r.session_id&&sessions.has(r.session_id)));const requestedIds=new Set(group.requests.map(r=>r.generation_id).filter(Boolean));group.generations=generations.filter(g=>(g.session_id&&sessions.has(g.session_id))||requestedIds.has(g.id))}
 setCustomers([...groups.values()].sort((a,b)=>Date.parse(b.leads[0].created_at)-Date.parse(a.leads[0].created_at)))}catch(e){logSupabaseError("load customer management",e);setError(e instanceof Error&&e.message==="TENANT_MEMBERSHIP_REQUIRED"?"برای این حساب هنوز عضویت سالن ثبت نشده است.":"دریافت اطلاعات مشتریان ممکن نشد. دسترسی Supabase را بررسی کنید.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function updateLead(id:string,value:Status){try{await rest(`leads?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({status:value})});setCustomers(rows=>rows.map(group=>({...group,leads:group.leads.map(lead=>lead.id===id?{...lead,status:value}:lead)})))}catch(e){logSupabaseError(`update lead ${id}`,e);setError("ذخیره وضعیت مشتری ممکن نشد.")}}
 async function updateRequest(id:string,value:string){try{await rest(`contact_requests?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({status:value})});setCustomers(rows=>rows.map(group=>({...group,requests:group.requests.map(request=>request.id===id?{...request,status:value}:request)})))}catch(e){logSupabaseError(`update contact request ${id}`,e);setError("ذخیره وضعیت درخواست ممکن نشد.")}}
 return <section className="customer-manager">{busy&&<div className="admin-notice">در حال دریافت پرونده مشتریان…</div>}{error&&<div className="form-error" role="alert">{error}</div>}{customers.map(customer=>{const lead=customer.leads[0];return <article className="customer-card" key={customer.key}><header><div><h2>{lead.name||"بدون نام"}</h2><p dir="ltr">{[lead.mobile,lead.whatsapp,lead.telegram].filter(Boolean).join(" · ")||"اطلاعات تماس ثبت نشده"}</p></div><strong>{customer.generations.length.toLocaleString("fa-IR")} شبیه‌سازی</strong></header><div className="customer-meta"><label>وضعیت ارتباط<select value={lead.status} onChange={e=>updateLead(lead.id,e.target.value as Status)}><option value="new">جدید</option><option value="contacted">تماس گرفته شد</option><option value="booked">رزرو شد</option><option value="closed">بسته شد</option></select></label><span>آخرین فعالیت: {formatDate(latestActivity(customer))}</span><span>خدمت: {lead.service_category_id?categories[lead.service_category_id]||"—":"—"}</span><span>انتخاب‌ها: {values(lead.selected_options)}</span></div>{customer.requests.length>0&&<section className="customer-requests"><h3>درخواست‌های مشاوره</h3>{customer.requests.map(request=><div key={request.id}><span>{formatDate(request.created_at)}{request.notes?` — ${request.notes}`:""}</span><select value={request.status} onChange={e=>updateRequest(request.id,e.target.value)}>{requestStatuses.map(status=><option value={status} key={status}>{status}</option>)}</select></div>)}</section>}<details><summary>تاریخچه شبیه‌سازی‌ها ({customer.generations.length.toLocaleString("fa-IR")})</summary>{customer.generations.length===0?<div className="empty-state">شبیه‌سازی مرتبطی ثبت نشده است.</div>:<div className="simulation-history">{customer.generations.map(g=>{const choice=g.choice_id?choices[g.choice_id]:undefined;return <article key={g.id} className={g.metadata?.liked===true?"liked-simulation":""}><div><b>{choice?.category_id?categories[choice.category_id]||"شبیه‌سازی":"شبیه‌سازی"}</b>{g.metadata?.liked===true&&<span className="liked-badge">♥ مورد علاقه مشتری</span>}<small>{formatDate(g.created_at)} · {g.status}</small><p>{values(choice?.selections)}</p></div><div className="customer-images">{g.input_url&&<figure><img src={g.input_url} alt="تصویر اصلی مشتری"/><figcaption>تصویر اصلی</figcaption></figure>}{g.output_url&&<figure><img src={g.output_url} alt="نتیجه شبیه‌سازی"/><figcaption>نتیجه</figcaption></figure>}</div></article>})}</div>}</details></article>})}{!busy&&!error&&!customers.length&&<div className="empty-state">هنوز مشتری‌ای ثبت نشده است.</div>}</section>
}
function values(value?:Record<string,string>){return value&&Object.keys(value).length?Object.values(value).join("، "):"—"}
function formatDate(value:string){return new Date(value).toLocaleString("fa-IR")}
function latestActivity(customer:Customer){return [...customer.leads,...customer.generations,...customer.requests].map(x=>x.created_at).sort().at(-1)||customer.leads[0].created_at}
