"use client";
import {useEffect,useState} from "react";
import {getContext} from "@/lib/admin/data";
import {logSupabaseError,rest} from "@/lib/supabase/client";

type ServiceCategory={id:string;name_fa:string|null;name_en:string|null;title:string;enabled:boolean;sort_order:number};

export function ServiceManager(){
 const [items,setItems]=useState<ServiceCategory[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pendingDisable,setPendingDisable]=useState<ServiceCategory|null>(null),[savingId,setSavingId]=useState<string|null>(null);
 async function load(){try{setBusy(true);setError("");const {tenantId}=await getContext();setItems(await rest<ServiceCategory[]>(`service_categories?select=id,name_fa,name_en,title,enabled,sort_order&tenant_id=eq.${tenantId}&order=sort_order.asc`))}catch(e){logSupabaseError("load admin services",e);setError("دریافت خدمات ممکن نشد. اتصال و دسترسی Supabase را بررسی کنید.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function patch(item:ServiceCategory,value:Partial<ServiceCategory>){const previous=items;setError("");setNotice("");setSavingId(item.id);setItems(rows=>rows.map(row=>row.id===item.id?{...row,...value}:row).sort((a,b)=>a.sort_order-b.sort_order));try{await rest(`service_categories?id=eq.${item.id}`,{method:"PATCH",body:JSON.stringify(value)});if(typeof value.enabled==="boolean")setNotice(value.enabled?"خدمت فعال شد و در اپ نمایش داده می‌شود.":"خدمت غیرفعال شد و دیگر در اپ نمایش داده نمی‌شود.")}catch(e){setItems(previous);logSupabaseError(`update service category ${item.id}`,e);setError("ذخیره تغییرات خدمت ممکن نشد؛ وضعیت قبلی بازگردانده شد.")}finally{setSavingId(null)}}
 const toggle=(item:ServiceCategory,enabled:boolean)=>{if(!enabled&&item.enabled){setPendingDisable(item);return}void patch(item,{enabled:true})};
 const confirmDisable=()=>{if(!pendingDisable)return;const item=pendingDisable;setPendingDisable(null);void patch(item,{enabled:false})};
 return <section className="admin-panel service-manager">{busy&&<div className="admin-notice">در حال دریافت خدمات…</div>}{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-note" role="status">{notice}</div>}<div className="service-editor-list">{items.map(item=><article key={item.id}><div className="form-grid"><Field label="نام فارسی" value={item.name_fa||item.title} save={name_fa=>patch(item,{name_fa})}/><Field label="نام انگلیسی" value={item.name_en||""} save={name_en=>patch(item,{name_en})}/><label>ترتیب نمایش<input type="number" value={item.sort_order} onChange={e=>patch(item,{sort_order:Number(e.target.value)})}/></label><label className="switch">فعال <input type="checkbox" checked={item.enabled} disabled={savingId===item.id} onChange={e=>toggle(item,e.target.checked)}/></label></div></article>)}</div>{!busy&&!error&&!items.length&&<div className="empty-state">خدمتی برای این سالن ثبت نشده است.</div>}{pendingDisable&&<div className="admin-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="disable-service-title"><div className="admin-confirm-modal"><h2 id="disable-service-title">غیرفعال کردن خدمت</h2><p>آیا مطمئن هستید می‌خواهید این خدمت غیرفعال شود؟<br/>این خدمت از اپ مشتریان پنهان می‌شود، اما اطلاعات و سوابق آن حذف نخواهد شد.</p><div><button onClick={()=>setPendingDisable(null)}>انصراف</button><button className="danger" onClick={confirmDisable}>بله، غیرفعال شود</button></div></div></div>}</section>
}
function Field({label,value,save}:{label:string;value:string;save:(value:string)=>void}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <label>{label}<input value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>draft!==value&&save(draft.trim())}/></label>}
