-- Multi-tenant foundation. Every user-owned business row is protected by tenant RLS.
create extension if not exists "pgcrypto";
create table salons (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, logo_url text, contact jsonb default '{}', theme jsonb default '{}', created_at timestamptz default now());
create table tenant_members (tenant_id uuid references salons on delete cascade, user_id uuid references auth.users on delete cascade, role text not null default 'admin', primary key(tenant_id,user_id));
create table consultant_profiles (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, name text not null, english_name text, avatar_url text, welcome_video_url text, poster_url text, welcome_message text, tone_of_voice text, video_enabled boolean default true, unique(tenant_id));
create table service_categories (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, slug text not null, title text not null, description text, icon text, sort_order int default 0, enabled boolean default true, unique(tenant_id,slug));
create table service_options (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, category_id uuid not null references service_categories on delete cascade, question_key text not null, label text not null, metadata jsonb default '{}', sort_order int default 0, enabled boolean default true);
create table anonymous_sessions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, intent text, generation_count int default 0, contact_unlocked boolean default false, expires_at timestamptz default now() + interval '30 days', created_at timestamptz default now());
create table leads (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, session_id uuid references anonymous_sessions on delete set null, name text, mobile text, whatsapp text, telegram text, consent_at timestamptz, created_at timestamptz default now());
create table consultations (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, session_id uuid references anonymous_sessions on delete set null, category_id uuid references service_categories on delete set null, answers jsonb not null default '{}', recommendations jsonb default '[]', status text default 'completed', created_at timestamptz default now());
create table user_choices (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, session_id uuid references anonymous_sessions on delete cascade, category_id uuid references service_categories on delete set null, path text check(path in ('consult','self')), selections jsonb not null default '{}', created_at timestamptz default now());
create table image_generations (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, session_id uuid references anonymous_sessions on delete set null, choice_id uuid references user_choices on delete set null, input_path text, output_path text, provider text default 'mock', status text default 'pending', metadata jsonb default '{}', permanent_storage_consent boolean default false, created_at timestamptz default now());
create table contact_requests (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, session_id uuid references anonymous_sessions on delete set null, lead_id uuid references leads on delete set null, generation_id uuid references image_generations on delete set null, status text default 'new', notes text, created_at timestamptz default now());
create table app_settings (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references salons on delete cascade, key text not null, value jsonb not null, unique(tenant_id,key));
create index on consultant_profiles(tenant_id); create index on service_categories(tenant_id); create index on service_options(tenant_id,category_id); create index on anonymous_sessions(tenant_id); create index on leads(tenant_id); create index on consultations(tenant_id); create index on user_choices(tenant_id); create index on image_generations(tenant_id); create index on contact_requests(tenant_id);

alter table salons enable row level security; alter table tenant_members enable row level security; alter table consultant_profiles enable row level security; alter table service_categories enable row level security; alter table service_options enable row level security; alter table anonymous_sessions enable row level security; alter table leads enable row level security; alter table consultations enable row level security; alter table user_choices enable row level security; alter table image_generations enable row level security; alter table contact_requests enable row level security; alter table app_settings enable row level security;
create or replace function is_tenant_member(tid uuid) returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from tenant_members where tenant_id=tid and user_id=auth.uid()) $$;
create policy "members read salons" on salons for select using(is_tenant_member(id));
create policy "members manage profiles" on consultant_profiles for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage categories" on service_categories for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage options" on service_options for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage sessions" on anonymous_sessions for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage leads" on leads for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage consultations" on consultations for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage choices" on user_choices for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage generations" on image_generations for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage requests" on contact_requests for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));
create policy "members manage settings" on app_settings for all using(is_tenant_member(tenant_id)) with check(is_tenant_member(tenant_id));

-- Demo data. Option rows are database-owned so the same frontend supports new services.
insert into salons(id,slug,name,theme) values ('00000000-0000-0000-0000-000000000001','demo','استودیو زیبایی مروا','{"background":"#f8f3e9","surface":"#fffdf8","accent":"#b49a68","text":"#352f2a"}');
insert into consultant_profiles(tenant_id,name,english_name,welcome_message) values ('00000000-0000-0000-0000-000000000001','مروا','Marvaa','سلام، من مروا هستم، خوش اومدی.');
insert into app_settings(tenant_id,key,value) values ('00000000-0000-0000-0000-000000000001','generation_limits','{"anonymous":1,"with_contact":3}');
